name: Docker image CI for monorepo

on:
  push:
    branches:
      - "main" # Trigger on pushes to the "main" branch
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push frontend image
      - name: Build and push (frontend)
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/frontend
          platforms: ${{ matrix.platform }}
          tags: ahmedmusa007/frontend:latest
          push: true

      # Build and push backend image
      - name: Build and push (backend)
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/backend
          platforms: ${{ matrix.platform }}
          tags: ahmedmusa007/backend:latest
          push: true
