version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: runner
    # command: yarn run migration:run
    env_file:
      - ./backend/.env.local
    ports:
      - 4000:4000
    networks:
      - my-app
    depends_on:
      - database

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: runner
      args:
        - API=http://localhost:4000/api/v1
    ports:
      - 3000:3000
    networks:
      - my-app
    depends_on:
      - backend

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - my-app

volumes:
  postgres-data:
    driver: local

networks:
  my-app:
